%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linacolucci/Desktop/subcu_thickness.xlsx
%    Worksheet: subcu
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/17 20:16:20

function subcuthickness = load_subcuthickness(pathToWorkbook, sheetName)

%% Check 
if ~isstring(pathToWorkbook) && ~ischar(pathToWorkbook)
    error('The ''pathToWorkbook'' is neither a string nor char')
end
if ~isstring(sheetName) && ~ischar(sheetName)
    error('The ''sheetName'' is neither a string nor char')
end

%% Import the data
try 
    [~, ~, raw] = xlsread(pathToWorkbook, sheetName); 
catch
    error('The specified excel workbook and sheet names do not point to a valid path that can be loaded.')
end
raw = raw(2:end,1:18);
stringVectors = string(raw(:,[1,5,6]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,7,8,9,10,11,12,13,14,15,16,17,18]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
subcuthickness = table;

%% Allocate imported array to column variable names
subcuthickness.Subject_Name = categorical(stringVectors(:,1));
subcuthickness.Subject = data(:,1);
subcuthickness.Visit_Num = data(:,2);
subcuthickness.HD = data(:,3);
subcuthickness.AMPM = categorical(stringVectors(:,2));
subcuthickness.Tissue = categorical(stringVectors(:,3));
subcuthickness.Slice1_a = data(:,4);
subcuthickness.Slice1_b = data(:,5);
subcuthickness.Slice1_c = data(:,6);
subcuthickness.Slice1_d = data(:,7);
subcuthickness.Slice2_a = data(:,8);
subcuthickness.Slice2_b = data(:,9);
subcuthickness.Slice2_c = data(:,10);
subcuthickness.Slice2_d = data(:,11);
subcuthickness.Slice3_a = data(:,12);
subcuthickness.Slice3_b = data(:,13);
subcuthickness.Slice3_c = data(:,14);
subcuthickness.Slice3_d = data(:,15);

%% Clear temporary variables
clearvars data raw stringVectors;